baseURL = "https://min3rd.github.io/arkham-city/"
languageCode = "en-us"
title = "Arkham City"
theme = "hugo-theme-learn"
contentDir = "docs/content"

# Enable search functionality
[outputs]
home = ["HTML", "RSS", "JSON"]

# Configure parameters
[params]
# Description of the site will be used in meta-information
description = "Documentation for the Arkham City project"
# Author of the site will be used in meta-information
author = "Arkham City Team"

# hugo-theme-learn parameters
# Change default color scheme with a variant one
themeVariant = "blue"
# Repository configuration for "Edit this page" links
editURL = "https://github.com/min3rd/arkham-city/edit/develop/docs/content/"
# Show a "Home" button in the menu
home_button_enabled = true

# For search functionality
[outputFormats.JSON]
baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true
