name: Update Contributors

on:
  push:
    branches:
      - develop

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          token: ${{ github.token }}

      - name: Set up Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Run update_contributors.sh
        run: |
          chmod +x ./update_contributors.sh
          ./update_contributors.sh

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create branch and push changes
        id: create_branch_and_push_changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # Create a new branch with a unique name based on the current date and time
          BRANCH_NAME="update-contributors-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME

          # Add, commit, and push changes to the new branch
          git add README.md
          git commit -m "Update Contributors section [skip ci]"
          git push https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git $BRANCH_NAME

          # Store the branch name for the next step
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH_NAME: ${{ steps.create_branch_and_push_changes.outputs.branch_name }}
        run: |
          # Install GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

          # Create pull request
          gh pr create \
            --title "Update Contributors section" \
            --body "This PR updates the Contributors section in the README.md file based on Git commit history.

            *This PR was automatically created by the Update Contributors GitHub Action.*" \
            --base develop \
            --head $BRANCH_NAME
